{% set name = "pyscaffoldext-markdown" %}
{% set version = "0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyscaffoldext-markdown-{{ version }}.tar.gz
  sha256: 7f2713b1cabdae350d162756c9ea07e10c1e76d85d09daaa8d70cef430b8b5db

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - importlib-metadata
    - myst-parser
    - pyscaffold >=4.1rc1,<5.0a0
    - python >=3.6
    - wheel >=0.31

test:
  imports:
    - pyscaffoldext
    - pyscaffoldext.markdown
  commands:
    - pip check
    - putup --help | grep markdown
    # PyScaffold uses Git, so add the necessary environment variables to configure it.
    - >
      GIT_COMMITTER_NAME="conda-forge tester" GIT_COMMITTER_EMAIL="tester@testing.com" GIT_AUTHOR_NAME="conda-forge tester" GIT_AUTHOR_EMAIL="tester@testing.com" pytest -m "not system and not slow" --cov-config setup.cfg
  source_files:
    - tests
    - setup.cfg
  requires:
    - pip
    - pytest
    - pytest-cov
    - git
    - tox
    - pre-commit
    - twine

about:
  home: https://github.com/pyscaffold/pyscaffoldext-markdown
  summary: PyScaffold extension which uses Markdown instead of reStructuredText
  dev_url: https://github.com/pyscaffold/pyscaffoldext-markdown/
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - maresb
    - FlorianWilhelm
    - abravalheri
