{% set name = "pyscaffoldext-markdown" %}
{% set version = "0.4.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyscaffoldext-markdown-{{ version }}.tar.gz
  sha256: 6959e5a3ebf2a7a2b1226a4071ecbb61e3e89358c68d1dcf3678f31fa1cd14ce

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - importlib-metadata
    - pyscaffold >=4.0b4,<5.0a0
    - python >=3.6
    - recommonmark
    - wheel >=0.31

test:
  imports:
    - pyscaffoldext
    - pyscaffoldext.markdown
  commands:
    - pip check
    - putup --help | grep markdown
    # PyScaffold uses Git, so add the necessary environment variables to configure it.
    - >
      GIT_COMMITTER_NAME="conda-forge tester" GIT_COMMITTER_EMAIL="tester@testing.com" GIT_AUTHOR_NAME="conda-forge tester" GIT_AUTHOR_EMAIL="tester@testing.com" pytest -m "not system and not slow" --cov-config setup.cfg
  source_files:
    - tests
    - setup.cfg
  requires:
    - pip
    - pytest
    - pytest-cov
    - git
    - tox
    - pre-commit
    - twine

about:
  home: https://github.com/pyscaffold/pyscaffoldext-markdown
  summary: PyScaffold extension which uses Markdown instead of reStructuredText
  dev_url: https://github.com/pyscaffold/pyscaffoldext-markdown/
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - maresb
    - FlorianWilhelm
    - abravalheri
